### PR TITLE
use system loguru

### LINKED ISSUE #154: Allow compiling with system-installed loguru
I am the Fedora package maintainer of j4-dmenu-desktop.

To allow distributions to package the upcoming release, there has to be a way to use a system-installed loguru.  Similarly as with catch2.

Aside: It's a little unfortunate that loguru was chosen, because it's not packaged in debian derivates (AFAICT) or Fedora and there is no released version.  But we'll deal with that.

### PR DESCRIPTION
**Pull request by ibotty**
only lightly tested.

meant to fix #154

### CODE REVIEW

**Comment by meator** [comment]
Hey. I have applied your commit 0e82a7c58785638b3c66f2ca18b9e0cbf2047747 which fixes the CMake typo. I did this because it is a severe problem with the build system, it isn't directly related to this pull request and pull request #156 already came up fixing the same problem. I don't want to make people fix a problem that has been already solved, so I have accepted that part of this pull request.

I have also force pushed to your branch, so be aware of that.

I am quite busy right now, I need more time to consider the rest of this pull request (using system loguru). But I will probably merge it in the foreseeable future. Thanks for fixing the CMake typo!

**Comment by ibotty** [comment]
NP.  Thank you for giving this consideration.  Nevertheless I am going to switch to meson as soon as loguru is accepted as new package.

**Comment by meator** [comment]
Note that Meson support will be added in the r3.0 release. I have several times stated that it's comming soon, but there is still some work to be done and as I said earlier, I'm quite busy now.

**Comment by ibotty** [comment]
Thank you for picking it up!  Take as much time as you want.  I intend to package a prerelease, because the last released version does not build anymore.  I hope you don't mind.

**Comment by meator** [comment]
This pull request got superseded by 5b5542f06d73abae3b516f8a8b9596f203d23b17 as I've mentioned in #154. I have tried to implement a similar change for spdlog to make a system installed version of it usable. But Meson should still be preferred.

**Pull request closed without merging**
